#####################################################################3

# Main.py related params
RUN_NEW : True
# True or False
# False will use the below DT_STRING
DT_STRING : "EDUCATION_22-09-2021_02-29-19"

# Name of the dataset
DATASET : "bank"
# OPTIONS: "adult", "credit", "LFW", "bank", "german", "statlog", "skillcraft"

# Name of Sensitive Attribute
ATTR : "EDUCATION"
# OPTIONS:
#   adult:      GENDER (2), RACE (5)
#   credit:     GENDER (2), EDUCATION (2)
#   LFW:        GENDER (2)
#   german:     AGE (2)
#   bank:       AGE (2), EDUCATION (2)
#   skillcraft: AGE (2)
#   statlog:    GENDER (2), AGE (2)
# bank 41188 x 20

# Values of k
K_VALS : [1]
# Standard: [4, 6, 8, 10, 12, 14, 16]
J_VALS : [1,2,4,6,8,10,12,15,20]
# 0: Clustering, >0 for Projective Clustering
Z : 2

NUM_INITS : 1
NUM_ITERS : 1

ALGOS : ["ALGO2","PCA"]
# OPTIONS:
#   Clustering: "Lloyd", "Fair-Lloyd", "ALGO", "ALGO2", "ALGO3"
#   Subspace Approximation: "PCA", "Fair-PCA", "ALGO"

# Sizes of Coresets
CORESET_SIZES : [1000]
CORESET_METHOD : "RANDOM"
# RANDOM, BLK17, FL11

# Apply PCA before algorithm starts
ISPCA : False

# Apply K-Means++ Initialization (Relevant to clustering)
ISKMEANSINIT : False

## ALGO2 related parameters ##
ALGO2_N_SAMPLES : 5
ALGO2_SAMPLE_SIZE : 1000

# Combine.py relevant
ITER_NUM : 1
ONLY_PLOT : False
FLAG : 0
# flag 0 - cost, flag 1 - only pca_cost, flag 2 - both